### ISSUE TITLE
Integrate with @pikapkg/cli - `pika init`?

### ISSUE THREAD

**Issue by ndom91** [ndom91/create-pika-app#8]
@FredKSchott you had mentioned you'd been thinking about adding some of these kinds of features to the `@pikapkg/cli` as `pika init`. 

I was just taking a look at the cli repo and noticed there is nothing like that in there yet. 

Is this still something you want to pursue? I can begin work on merging the functionality from this into the pika cli under an `init` command.

p.s. sorry for blowing up your github notifications lately :joy:

**Comment by FredKSchott** [comment]
Haha no problem at all! Just commented in another thread, but I've been traveling and less responsive this last week. This is a great idea and definitely the direction I'd like to see this going. I'd love if this package could become the new `pika init` command. 

Currently, all of our CLI tools (install, pack) use the following pattern:

1. Main logic is published to `@pika/CMD` (in this case, `@pika/init`). This lets anyone try the tool out directly as just `npx @pika/init`.
2. A command is added to @pika/cli, so that any of our Pika CLI users can use `pika init`. This is especially useful in build scripts (`"build": "pika pack") and the multi-use case.

So then I guess the first question then is do you feel comfortable moving this package/repo into the official @pika/@pikapkg org/scope? You'd obviously stay on as a full contributor/owner of the repo/package, but then this would allow us to publish it as `@pika/init` and match the other official packages.

**Comment by ndom91** [comment]
Ah okay so thats how it works! I didnt quite understand the structure of pika init vs @pika/init until that explanation haha.

But anyway, yeah thats alright with me, just let me know what I need to do on my end in regard to moving the repo, etc.

**Comment by FredKSchott** [comment]
Yea I know, our cross-project documentation continues to be a weak spot. But each README individually explains how to use each library, so hopefully most people aren't affected.

I *think* you can initiate the transfer to the `pikapkg` org on GitHub from within the repo settings page. Otherwise, if you give me edit permissions on this repo I may be able to do it. tbh I'm not sure, I don't do this very often :) These seem to be the docs on it: https://help.github.com/en/articles/transferring-a-repository

**Comment by ndom91** [comment]
All good, I just didnt put 2 and 2 together haha.

So I tried to transfer it to `pikapkg`, but there is a `create-pika-app` in `pikapkg` already from the time you forked this repo for the PR. Can you delete that and let me know? Ill try again then.

**Comment by ndom91** [comment]
@FredKSchott friendly reminder to delete @pikapkg/create-pika-app so i can transfer the repo to you ;)

**Comment by FredKSchott** [comment]
@ndom91 bah, sorry for the delay! No longer traveling so should be much more responsive. 

The fork has been deleted, go go go!!!

**Comment by ndom91** [comment]
Haha thanks. Apparently I need permissions to create public repos at 'pikapkg' too?
![screenshot_2019-09-30_18-44-36](https://user-images.githubusercontent.com/7415984/65898684-6930cb00-e3b2-11e9-96b7-e25ac9ecc714.png)

**Comment by FredKSchott** [comment]
lol 1 sec I'll add you as a maintainer
Edit: Done!

**Comment by ndom91** [comment]
Incoming :rocket:

![screenshot_2019-09-30_18-50-52](https://user-images.githubusercontent.com/7415984/65899097-4eab2180-e3b3-11e9-82b3-5a2be6bebd0e.png)

**Comment by FredKSchott** [comment]
Success! Also, love the new README!

Can you rename the repo to `init` to match the others, and then whenever you're ready I'll publish to npm under `@pika/init`?

**Comment by ndom91** [comment]
Sure thing. I think I'm missing some rights though. I don't have a settings tab for the repo anymore

**Comment by FredKSchott** [comment]
try now, added you as a full admin for the repo

**Comment by ndom91** [comment]
🙌🏾🙌🏾🙌🏾

**Comment by FredKSchott** [comment]
Great! I'll create a PR for @pika/cli now

**Comment by FredKSchott** [comment]
CLI change merged to master [here](https://github.com/pikapkg/cli/blob/217f791176957b00f2dd3ff332dac08ab05cac66/src/index.ts#L67-L71).
PR for updating the @pika/init package.json: #9 (review needed)

That should be all that we need to publish!

**Comment by ndom91** [comment]
Alright great. Looks good to me!
